INSERT INTO players (id, name, active, strong_foot, notes, created_at, updated_at) VALUES
(1,  'Kobi',       true, 'Right', 'Most MVPs. CM/CDM.',   NOW(), NOW()),
(2,  'Aqib',       true, 'Right', 'Forward',              NOW(), NOW()),
(3,  'Safi',       true, 'Right', 'LB/CDM',               NOW(), NOW()),
(4,  'Hasnain',    true, 'Right', 'LM/RM',                NOW(), NOW()),
(5,  'Aks',        true, 'Right', 'CAM',                  NOW(), NOW()),
(6,  'Akshay',     true, 'Right', 'CAM/ST',               NOW(), NOW()),
(7,  'Arif',       true, 'Right', 'Defender',             NOW(), NOW()),
(8,  'Fin',        true, 'Right', 'Finisher',             NOW(), NOW()),
(9,  'Ibrahim',    true, 'Right', 'Finisher',             NOW(), NOW()),
(10, 'Isa',        true, 'Right', 'CAM/CM',               NOW(), NOW()),
(11, 'Jana',       true, 'Right', 'Defender',             NOW(), NOW()),
(12, 'Mashkoor',   true, 'Right', 'CM',                   NOW(), NOW()),
(13, 'Mat',        true, 'Right', 'CAM/CM',               NOW(), NOW()),
(14, 'Nabeel',     true, 'Right', 'Midfielder/ST',        NOW(), NOW()),
(15, 'Shahan',     true, 'Right', 'DEF/CM',               NOW(), NOW()),
(16, 'Syed',       true, 'Right', 'Defender',             NOW(), NOW()),
(17, 'Toni',       true, 'Right', 'CM',                   NOW(), NOW()),
(18, 'Sa''ad',     true, 'Left',  'LB/RM',                NOW(), NOW()),
(19, 'Akhil',      true, 'Right', 'Defender',             NOW(), NOW()),
(20, 'Corey',      true, 'Right', 'LM',                   NOW(), NOW()),
(21, 'Danvir',     true, 'Right', 'Defender',             NOW(), NOW()),
(22, 'Ryan',       true, 'Right', 'Midfielder/ST',        NOW(), NOW()),
(23, 'Faheem',     true, 'Right', 'Finisher',             NOW(), NOW()),
(24, 'Govin',      true, 'Right', 'Attacker',             NOW(), NOW()),
(25, 'Jag',        true, 'Right', 'Defender/Finisher',    NOW(), NOW()),
(26, 'Jahansher',  true, 'Right', 'CAM/Finisher',         NOW(), NOW()),
(27, 'Munawar',    true, 'Right', 'Controller/Finisher',  NOW(), NOW()),
(28, 'Sahi',       true, 'Right', 'LM',                   NOW(), NOW()),
(29, 'Yusuf',      true, 'Right', 'Defender',             NOW(), NOW()),
(30, 'Yuv',        true, 'Right', 'Defender',             NOW(), NOW()),
(31, 'Raf',        true, 'Right', 'Defender',             NOW(), NOW()),
(32, 'Josh',       true, 'Right', 'Defender',             NOW(), NOW()),
(33, 'Abdi',       true, 'Right', 'Finisher',             NOW(), NOW()),
(34, 'Mit',        true, 'Left',  'RB',                   NOW(), NOW()),
(35, 'Nim',        true, 'Right', 'GK',                   NOW(), NOW()),
(36, 'Abdulmalik', true, 'Right', 'Defender',             NOW(), NOW()),
(37, 'Jamie',      true, 'Right', 'Midfielder',           NOW(), NOW()),
(38, 'Hassan',     true, 'Right', 'RB/Midfielder',        NOW(), NOW()),
(39, 'Suvi',       true, 'Right', 'Midfielder',           NOW(), NOW());

SELECT setval('players_id_seq', 39);