INSERT INTO players (id, name, active, strong_foot, notes, position, created_at, updated_at) VALUES
(1,  'Kobi',       true,  'Right', 'Most MVPs. CM/CDM.',   'CDM',     NOW(), NOW()),
(2,  'Aqib',       true,  'Right', 'Forward',              'ST',      NOW(), NOW()),
(3,  'Safi',       true,  'Right', 'LB/CDM',               'LB',      NOW(), NOW()),
(4,  'Hasnain',    true,  'Right', 'LM/RM',                'RW',      NOW(), NOW()),
(5,  'Akash',      true,  'Right', 'CAM',                  'CAM',     NOW(), NOW()),
(6,  'Akshay',     true,  'Right', 'CAM/ST',               'CAM',     NOW(), NOW()),
(7,  'Arif',       true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(8,  'Finlay',     true,  'Right', 'Finisher',             'ST',      NOW(), NOW()),
(9,  'Ibrahim',    true,  'Right', 'Finisher',             'ST',      NOW(), NOW()),
(10, 'Isa',        true,  'Right', 'CAM/CM',               'CAM',     NOW(), NOW()),
(11, 'Jana',       true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(12, 'Mashkoor',   true,  'Right', 'CM',                   'CDM',     NOW(), NOW()),
(13, 'Matt',       true,  'Right', 'CAM/CM',               'CAM',     NOW(), NOW()),
(14, 'Nabeel',     true,  'Right', 'Midfielder/ST',        'LW',      NOW(), NOW()),
(15, 'Shahan',     true,  'Right', 'DEF/CM',               'CDM',     NOW(), NOW()),
(16, 'Syed',       true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(17, 'Toni',       true,  'Right', 'CM',                   'CM',      NOW(), NOW()),
(18, 'Sa''ad',     true,  'Left',  'LB/RM',                'LB',      NOW(), NOW()),
(19, 'Akhil',      true,  'Right', 'Defender',             'RB',      NOW(), NOW()),
(20, 'Corey',      true,  'Right', 'LM',                   'RW',      NOW(), NOW()),
(21, 'Danvir',     true,  'Right', 'Defender',             'LB',      NOW(), NOW()),
(22, 'Ryan',       true,  'Right', 'Midfielder/ST',        'LW',      NOW(), NOW()),
(23, 'Faheem',     true,  'Right', 'Finisher',             'ST',      NOW(), NOW()),
(24, 'Govin',      true,  'Right', 'Attacker',             'ST',      NOW(), NOW()),
(25, 'Jag',        true,  'Right', 'Defender/Finisher',    'LB',      NOW(), NOW()),
(27, 'Munawar',    true,  'Right', 'Controller/Finisher',  'CAM',     NOW(), NOW()),
(28, 'Sahi',       true,  'Right', 'LM',                   'LW',      NOW(), NOW()),
(29, 'Yusuf',      true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(30, 'Yuvraj',     true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(31, 'Raf',        true,  'Right', 'Defender',             'LW',      NOW(), NOW()),
(32, 'Josh',       true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(33, 'Abdi',       true,  'Right', 'Finisher',             'ST',      NOW(), NOW()),
(34, 'Mit',        true,  'Left',  'RB',                   'RB',      NOW(), NOW()),
(35, 'Nimanka',    true,  'Right', 'GK',                   'GK',      NOW(), NOW()),
(36, 'Abdulmalik', true,  'Right', 'Defender',             'CB',      NOW(), NOW()),
(37, 'Jamie',      true,  'Right', 'Midfielder',           'CM',      NOW(), NOW()),
(38, 'Hassan',     true,  'Right', 'RB/Midfielder',        'RB',      NOW(), NOW()),
(39, 'Suvi',       true,  'Right', 'Midfielder',           'ST',      NOW(), NOW()),
(40, 'AJ',         false, 'Right', 'Unknown',              'CM',      NOW(), NOW()),
(41, 'Ali Zeb',    false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(42, 'Aman',       false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(43, 'Arashdeep',  false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(44, 'Arish',      false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(45, 'Ayush',      false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(46, 'Biranavan',  false, 'Right', 'Unknown',              'RB',      NOW(), NOW()),
(47, 'Haaris Raza',  false, 'Right', 'Unknown',            'ST',      NOW(), NOW()),
(48, 'Haaris Usman', false, 'Right', 'Unknown',            'ST',      NOW(), NOW()),
(49, 'Hamza',      false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(50, 'Hanish',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(51, 'Harith',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(52, 'Hassan Ali', false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(53, 'Ilyas',      false, 'Right', 'Unknown',              'CM',      NOW(), NOW()),
(54, 'Ismail',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(55, 'Jay',        true, 'Right', 'CAM/Finisher',          'CM',      NOW(), NOW()),
(56, 'Joe',        false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(57, 'Kishan',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(58, 'Mohammed',   false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(59, 'Raess',      false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(60, 'Ravi',       false, 'Right', 'Unknown',              'CDM',     NOW(), NOW()),
(61, 'Ruben',      false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(62, 'Shoaib',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(63, 'Tahmid',     false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(64, 'Umar',       false, 'Right', 'Unknown',              'UNKNOWN', NOW(), NOW()),
(65, 'Vithu',      false, 'Right', 'Unknown',              'RW',      NOW(), NOW()),
(66, 'Yousaf',     false, 'Right', 'Unknown',              'CB',      NOW(), NOW()),
(67, 'Zain',       false, 'Right', 'Unknown',              'RB',      NOW(), NOW()),
(68, 'Junaid',     true,  'Right', 'Midfielder',             'UNKNOWN', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    position = EXCLUDED.position;

SELECT setval('players_id_seq', 68);