INSERT INTO players (id, name, active, strong_foot, position, created_at, updated_at) VALUES
(1,  'Kobi',       true,  'Right', 'CDM',     NOW(), NOW()),
(2,  'Aqib',       true,  'Right', 'ST',      NOW(), NOW()),
(3,  'Safi',       true,  'Right', 'LB',      NOW(), NOW()),
(4,  'Hasnain',    true,  'Right', 'RW',      NOW(), NOW()),
(5,  'Akash',      true,  'Right', 'CAM',     NOW(), NOW()),
(6,  'Akshay',     true,  'Right', 'CAM',     NOW(), NOW()),
(7,  'Arif',       true,  'Right', 'CB',      NOW(), NOW()),
(8,  'Finlay',     true,  'Right', 'ST',      NOW(), NOW()),
(9,  'Ibrahim',    true,  'Right', 'ST',      NOW(), NOW()),
(10, 'Isa',        true,  'Right', 'CAM',     NOW(), NOW()),
(11, 'Jana',       true,  'Right', 'CB',      NOW(), NOW()),
(12, 'Mashkoor',   true,  'Right', 'CDM',     NOW(), NOW()),
(13, 'Matt',       true,  'Right', 'CAM',     NOW(), NOW()),
(14, 'Nabeel',     true,  'Right', 'LW',      NOW(), NOW()),
(15, 'Shahan',     true,  'Right', 'CDM',     NOW(), NOW()),
(16, 'Syed',       true,  'Right', 'CB',      NOW(), NOW()),
(17, 'Toni',       true,  'Right', 'CM',      NOW(), NOW()),
(18, 'Sa''ad',     true,  'Left',  'LB',      NOW(), NOW()),
(19, 'Akhil',      true,  'Right', 'RB',      NOW(), NOW()),
(20, 'Corey',      true,  'Right', 'RW',      NOW(), NOW()),
(21, 'Danvir',     true,  'Right', 'LB',      NOW(), NOW()),
(22, 'Ryan',       true,  'Right', 'LW',      NOW(), NOW()),
(23, 'Faheem',     true,  'Right', 'ST',      NOW(), NOW()),
(24, 'Govin',      true,  'Right', 'ST',      NOW(), NOW()),
(25, 'Jag',        true,  'Right', 'LB',      NOW(), NOW()),
(27, 'Munawar',    true,  'Right', 'CAM',     NOW(), NOW()),
(28, 'Sahi',       true,  'Right', 'LW',      NOW(), NOW()),
(29, 'Yusuf',      true,  'Right', 'CB',      NOW(), NOW()),
(30, 'Yuvraj',     true,  'Right', 'CB',      NOW(), NOW()),
(31, 'Raf',        true,  'Right', 'LW',      NOW(), NOW()),
(32, 'Josh',       true,  'Right', 'CB',      NOW(), NOW()),
(33, 'Abdi',       true,  'Right', 'ST',      NOW(), NOW()),
(34, 'Mit',        true,  'Left',  'RB',      NOW(), NOW()),
(35, 'Nimanka',    true,  'Right', 'GK',      NOW(), NOW()),
(36, 'Abdulmalik', true,  'Right', 'CB',      NOW(), NOW()),
(37, 'Jamie',      true,  'Right', 'CM',      NOW(), NOW()),
(38, 'Hassan',     true,  'Right', 'RB',      NOW(), NOW()),
(39, 'Suvi',       true,  'Right', 'ST',      NOW(), NOW()),
(40, 'AJ',         false, 'Right', 'CM',      NOW(), NOW()),
(41, 'Ali Zeb',    false, 'Right', 'UNKNOWN', NOW(), NOW()),
(42, 'Aman',       false, 'Right', 'UNKNOWN', NOW(), NOW()),
(43, 'Arashdeep',  false, 'Right', 'UNKNOWN', NOW(), NOW()),
(44, 'Arish',      false, 'Right', 'UNKNOWN', NOW(), NOW()),
(45, 'Ayush',      false, 'Right', 'UNKNOWN', NOW(), NOW()),
(46, 'Biranavan',  false, 'Right', 'RB',      NOW(), NOW()),
(47, 'Haaris Raza',  false, 'Right', 'ST',    NOW(), NOW()),
(48, 'Haaris Usman', false, 'Right', 'ST',    NOW(), NOW()),
(49, 'Hamza',      false, 'Right', 'UNKNOWN', NOW(), NOW()),
(50, 'Hanish',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(51, 'Harith',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(52, 'Hassan Ali', false, 'Right', 'UNKNOWN', NOW(), NOW()),
(53, 'Ilyas',      false, 'Right', 'CM',      NOW(), NOW()),
(54, 'Ismail',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(55, 'Jay',        true,  'Right', 'CM',      NOW(), NOW()),
(56, 'Joe',        false, 'Right', 'UNKNOWN', NOW(), NOW()),
(57, 'Kishan',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(58, 'Mohammed',   false, 'Right', 'UNKNOWN', NOW(), NOW()),
(59, 'Raess',      false, 'Right', 'UNKNOWN', NOW(), NOW()),
(60, 'Ravi',       false, 'Right', 'CDM',     NOW(), NOW()),
(61, 'Ruben',      false, 'Right', 'UNKNOWN', NOW(), NOW()),
(62, 'Shoaib',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(63, 'Tahmid',     false, 'Right', 'UNKNOWN', NOW(), NOW()),
(64, 'Umar',       false, 'Right', 'UNKNOWN', NOW(), NOW()),
(65, 'Vithu',      false, 'Right', 'RW',      NOW(), NOW()),
(66, 'Yousaf',     false, 'Right', 'CB',      NOW(), NOW()),
(67, 'Zain',       false, 'Right', 'RB',      NOW(), NOW()),
(68, 'Junaid',     true,  'Right', 'CM',      NOW(), NOW()),
(69, 'Misbahul',   true,  'Right', 'ST',      NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
    position = EXCLUDED.position;

SELECT setval('players_id_seq', 69);